# Generated by Django 3.2.6 on 2021-08-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
