# Generated by Django 3.2.6 on 2021-08-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_file_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='fileList',
        ),
    ]
